# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org:
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app:
# "service" is the name of this project. This will also be added to your AWS resource names.
service:

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: ''

frameworkVersion: '^4'
plugins:
  - serverless-lambda-edge-pre-existing-cloudfront

functions:
  imageResize:
    name: 'lambda-test'
    handler: handler.imageResize
    events:
      - preExistingCloudFront:
          distributionId:
          eventType: origin-response
          pathPattern: '*'
          includeBody: false
