name: build-on-tag-push-backend

on:
  push:
    tags:
      - 'back-*'

jobs:
  back-build:
    if: startsWith(github.ref, 'refs/tags/back-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Extract tag
        run: |
          TAG=$(echo $GITHUB_REF | cut -d '/' -f 3 | cut -d '-' -f 2)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: build docker image
        run: |
          docker build -t photograph-server:$TAG .
